# Generated by Django 4.0.3 on 2022-03-01 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quote", models.TextField()),
                ("no_of_letters", models.IntegerField()),
                ("no_of_vowels", models.IntegerField()),
                ("no_of_consonants", models.IntegerField()),
                ("count_of_all_letters", models.JSONField()),
                (
                    "avg_len_of_words",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("three_longest_words", models.CharField(max_length=250)),
            ],
        ),
    ]
