version: '3.9'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
    - 8000:8000

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: reviro_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=reviro
      - POSTGRES_DB=reviro
    
volumes:
  postgres_data: