on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ${{ secrets.DIGITAL_OCEAN_REGISTRY }}
  DOC_API_TOKEN: ${{ secrets.DOC_API_TOKEN }}


jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo 
        uses: actions/checkout@v2
        
      - name: Build container image
        run: docker build -t finkg-back:latest .
    
      - name: Log in to DigitalOcean Container Registry with access token
        run: docker login -u $DOC_API_TOKEN -p $DOC_API_TOKEN registry.digitalocean.com
      
      - name: Tag image
        run: docker tag finkg-back:latest registry.digitalocean.com/$REGISTRY/finkg-back:latest
        
      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/$REGISTRY/finkg-back:latest

 
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script_stop: true
          envs: REGISTRY, DOC_API_TOKEN
          script: |
            docker login -u $DOC_API_TOKEN -p $DOC_API_TOKEN registry.digitalocean.com
            docker pull registry.digitalocean.com/$REGISTRY/finkg-back:latest
            docker-compose up -d
            docker-compose restart